### ISSUE TITLE
Atlas DBN labels  

### ISSUE THREAD

**Issue by kschan0214** [chewnglow/MuSus-100_Atlas#1]
Hi, thank you very much for sharing the atlas and labels!

For my understanding (and also indicated in the label text files), the structures with an odd-numbered index corresponding to the location in the left hemisphere, while those with an even-numbered index corresponding to the right hemisphere. However, the indices in the DBN NIFTI file are left-right swapped (even numbers on the left while odd numbers on the right, see attached image). I was wondering if it is the case that the labels are incorrectly (left-right) swapped in the DBN.nii.gz (and the DBN in mixed.nii.gz) or the indices in the NIFTI file are correct but the geometry info of the NIFTI file was incorrectly exported?

Thanks in advanced for you help!

Kwok 

![Screenshot 2022-11-07 161608](https://user-images.githubusercontent.com/39571502/200346359-f75ce281-5d9d-454a-8b9a-581d0a1c2959.png)

**Comment by chewnglow** [comment]
Hi Kwok, thank you for the correction! There is indeed a bug in the label description that oppositely marks the nuclei's semi-hemisphere. The issue has been fixed in the latest release, along with some label gimmicks. Please refer to the updated version. 

We shall close the issue currently. Feel free to reply if you still have problems. 

Chenyu
